### ISSUE TITLE
Ability to download locally?

### ISSUE THREAD

**Issue by ajb** [dethcrypto/dethcode#72]
deth.net is a lifesaver - does anyone know if there is the ability to automatically download the files and open them in your *local* VS Code instance? can't seem to figure this out, any advice is appreciated :)

**Comment by ksin751119** [comment]
I have the same issue...

**Comment by abmisx0** [comment]
same here, what's the easiest way to do this? Right now I have to manually create the file directories and then download each file. Can we get a clone repo feature please.

**Comment by Elyx0** [comment]
Been waiting a long time for dethcode to solve this, @abmisx0 i use blockscan instead now when I want to download https://vscode.blockscan.com/ethereum/0xba12222222228d8ba445958a75a0704d566bf2c8 

in dethcode doing the same as blockscan you get a console error of cross origin
```
 WARN DOMException: Failed to execute 'showDirectoryPicker' on 'Window': Cross origin sub frames aren't allowed to show a file picker.
    at B.i (https://code.deth.net/out/vs/workbench/workbench.web.main.js:2551:118413)
    at async B.h (https://code.deth.net/out/vs/workbench/workbench.web.main.js:2551:118137)
``` o

**Comment by Mouradif** [comment]
This is because when you access `some-explorer.deth.net/address/<address>`, it opens a web page with an iframe that points to the correct URL: `code.deth.net/address/<address>?explorer=some-explorer`. Since the iframe is technically showing a different domain, the browser refuses to show the picker that lets you give access to some folder of your file system to the webpage.

Interestingly enough, I tried going directly to the url from the iframe, I selected "Download", it showed the native file system dialog to select a folder, but then it just kept loading forever
